# Generated by Django 4.1 on 2022-09-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthEduApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
