# Generated by Django 4.1 on 2022-09-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthEduApp', '0002_remove_message_title_alter_message_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'courses'},
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
